
from nltk.chat.util import Chat, reflections

pairs = [
    ['hi|hello|hey', ['Hello!', 'Hi there!', 'Hey!']],
    ['how are you?', ['I am good, thank you!', 'Fine, thanks!', 'I am doing well.']],
    ['what\'s up?', ['Not much, how about you?', 'Just chilling, what about you?', 'Nothing much, just here.']],
    ['how\'s it going?', ['Going well, how about you?', 'Pretty good, thanks for asking.', 'Can\'t complain, what about you?']],
    ['how are you doing today?', ['I am doing great today!', 'Feeling fantastic, thanks for asking.', 'Having a good day, thanks.']],
    ['what are you up to?', ['Just here to help you out!', 'Nothing much, just assisting users like you.', 'Just being a virtual assistant!']],
    ['bye|goodbye', ['Goodbye!', 'See you later!', 'Take care!']],
    ['see you later|talk to you later', ['Sure, take care!', 'Until next time!', 'Bye for now!']],
    ['what can you do?', ['I can help with tasks like scheduling, providing information, and more. Just ask!', 'I can assist with various tasks such as scheduling, providing recommendations, and more.']],
    ['thanks|thank you', ['You\'re welcome!', 'No problem!', 'Happy to help!']],
    ['sorry', ['No worries!', 'It\'s alright.', 'No problem at all.']],
    ['tell me a joke', ['Why don\'t skeletons fight each other? They don\'t have the guts.', 'What do you call fake spaghetti? An impasta.', 'Why did the scarecrow win an award? Because he was outstanding in his field.']],
    ['do you know any riddles?', ['What has keys but can\'t open locks? A piano.', 'What has a head and a tail, but no body? A coin.', 'The more you take, the more you leave behind. What am I? Footsteps.']],
    ['what\'s the weather like today?', ['You might want to bring an umbrella, it looks like it might rain.', 'It\'s sunny and warm today, perfect weather for a stroll.', 'It\'s pretty chilly today, make sure to bundle up.']],
    ['what time is it?', ['It\'s currently {time}.', 'The time is {time}.', 'According to my clock, it\'s {time}.']],
    ['can you schedule a meeting for me?', ['Sure, please provide the details of the meeting.', 'Of course, let me know the date and time you\'d like the meeting to be scheduled.']],
    ['remind me to call John at 5 PM', ['Got it, I\'ll remind you to call John at 5 PM.', 'Reminder set to call John at 5 PM.', 'Noted, I\'ll remind you to call John at 5 PM.']],
    ['what movies are playing nearby?', ['Let me check for you. Please wait a moment.', 'Checking the movie listings for you.', 'One moment while I fetch the movie listings.']],
    ['can you recommend a good restaurant?', ['Sure, what type of cuisine are you in the mood for?', 'I can recommend several restaurants based on your preferences. What type of food do you like?']],
    ['how do I change my password?', ['You can change your password by going to the settings page and selecting the password option.', 'To change your password, navigate to your account settings and look for the password section.']],
    ['can you set an alarm for 7 AM tomorrow?', ['Alarm set for 7 AM tomorrow.', 'You got it, alarm set for 7 AM tomorrow.', 'Done, I\'ve set the alarm for 7 AM tomorrow.']],
    ['what\'s the meaning of life?', ['That\'s a tough question! Philosophers have debated it for centuries.']],
    ['tell me a fun fact', ['Did you know that honey never spoils? Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible.']],
    ['what\'s your favorite color?', ['As a virtual assistant, I don\'t have personal preferences, but I think all colors are beautiful!']],
    ['who created you?', ['I was created by a team of developers at OpenAI.', 'My creators are a talented group of engineers and researchers at OpenAI.']],
    ['are you a robot?', ['I\'m not a robot in the traditional sense, but I am powered by artificial intelligence.', 'I\'m an AI virtual assistant, so I guess you could say I\'m a robot in a way.']],
    ['can you sing a song?', ['I\'m afraid I don\'t have a singing voice, but I can provide song recommendations if you\'d like!', 'I\'m not much of a singer, but I can try to find some lyrics for you.']],
    ['what\'s your favorite movie?', ['As a virtual assistant, I don\'t have personal preferences, but I can recommend some popular movies if you\'re interested.']],
    ['do you dream?', ['I don\'t have the capability to dream like humans do, but I\'m always here to help you achieve your goals!', 'Dreaming is a human experience, but I\'m here to help you turn your dreams into reality.']],
    ['tell me a story', ['Once upon a time, in a faraway land, there was a brave knight who embarked on a quest to rescue a captured princess...', 'There once was a wise old owl who lived in the heart of a magical forest...']],
    ['what\'s the capital of France?', ['The capital of France is Paris.', 'Paris is the capital of France.', 'France\'s capital city is Paris.']],
    ['how do I cook pasta?', ['To cook pasta, bring a pot of water to a boil, add a pinch of salt, then add the pasta and cook until it reaches your desired level of tenderness.']],
    ['can you help me with my homework?', ['I can certainly try! What subject are you working on?', 'I\'ll do my best to assist you. What do you need help with?']],
    ['what\'s the tallest mountain in the world?', ['Mount Everest is the tallest mountain in the world.', 'The highest peak on Earth is Mount Everest.']],
    ['how do I say "hello" in Spanish?', ['"Hello" in Spanish is "Hola".', 'The Spanish word for "hello" is "Hola".']],
    ['what\'s the square root of 144?', ['The square root of 144 is 12.', '144\'s square root is 12.', 'It\'s 12, the square root of 144.']],
    ['can you help me find a job?', ['I can provide tips and resources for job hunting if you\'d like!', 'I can assist you with your job search. What type of job are you looking for?']],
    ['what\'s the population of China?', ['China\'s population is over 1.4 billion people.', 'Over 1.4 billion people live in China.']],
    ['how do I get to the nearest post office?', ['I can help you find directions to the nearest post office. Please provide your current location.']],
    ['what\'s the best way to learn programming?', ['The best way to learn programming varies from person to person, but resources like online courses, tutorials, and practice projects can be helpful.']],
    ['can you tell me about the history of the internet?', ['The internet was developed in the late 1960s and early 1970s as a network for military and academic research purposes.']],
    ['what\'s your favorite book?', ['As a virtual assistant, I don\'t have personal preferences, but I can recommend some popular books if you\'re interested.']],
    ['how do I meditate?', ['To meditate, find a quiet and comfortable space, focus on your breath, and let go of any thoughts or distractions.']],
    ['what\'s the distance between the Earth and the moon?', ['On average, the distance between the Earth and the moon is about 238,855 miles (384,400 kilometers).']],
    ['how do I tie a tie?', ['There are several ways to tie a tie, but a common method is the four-in-hand knot.']],
    ['what\'s the difference between weather and climate?', ['Weather refers to short-term atmospheric conditions, while climate refers to long-term patterns and trends.']],
    ['can you help me with a math problem?', ['I\'ll do my best to assist you. What\'s the math problem?']],
    ['what\'s the meaning of the word "serendipity"?', ['Serendipity refers to the occurrence of fortunate events by chance.']],
    ['how do I improve my memory?', ['Practicing techniques such as visualization, association, and repetition can help improve memory.']],
    ['what\'s the best way to stay motivated?', ['Setting clear goals, staying organized, and finding inspiration from others can help you stay motivated.']],
    ['can you recommend a good podcast?', ['Sure! What are you interested in?']],
    ['what\'s the difference between a crocodile and an alligator?', ['Crocodiles have a V-shaped snout, while alligators have a U-shaped snout.']],
    ['what\'s the capital of Australia?', ['The capital of Australia is Canberra.']],
    ['can you help me find a place to volunteer?', ['There are many websites that can help you find volunteer opportunities in your area.']],
    ['what\'s the largest desert in the world?', ['The largest desert in the world is the Sahara Desert.']],
    ['how do I start a blog?', ['Starting a blog involves choosing a topic, selecting a platform, and creating content.']],
    ['can you recommend a good movie to watch?', ['Sure, what genre are you in the mood for?']],
    ['what\'s the difference between a fruit and a vegetable?', ['Fruits develop from the ovary of a flowering plant and contain seeds, while vegetables consist of other plant parts such as roots, stems, and leaves.']],
    ['what\'s the capital of Brazil?', ['The capital of Brazil is Brasília.']],
    ['can you help me find a good workout routine?', ['There are many resources available online for finding workout routines tailored to your fitness goals and preferences.']],
    ['what\'s the speed of light?', ['The speed of light in a vacuum is approximately 299,792 kilometers per second (about 186,282 miles per second).']],
    ['how do I start a small business?', ['Starting a small business involves creating a business plan, registering your business, and obtaining any necessary permits or licenses.']],
    ['what\'s the tallest building in the world?', ['As of now, the tallest building in the world is the Burj Khalifa in Dubai, United Arab Emirates.']],
    ['can you help me find a good book to read?', ['Sure, what genre do you enjoy?']],
    ['what\'s the difference between a turtle and a tortoise?', ['Turtles are adapted for life in the water, while tortoises are adapted for life on land.']],
    ['what\'s the capital of Canada?', ['The capital of Canada is Ottawa.']],
    ['how do I cook rice?', ['To cook rice, rinse it thoroughly, add it to a pot with water, and simmer until the water is absorbed and the rice is tender.']],
    ['what\'s the largest ocean in the world?', ['The largest ocean in the world is the Pacific Ocean.']],
    ['can you help me find a good recipe?', ['Sure, what type of cuisine are you interested in?']],
    ['what\'s the difference between a psychologist and a psychiatrist?', ['Psychologists study human behavior and mental processes, while psychiatrists are medical doctors who can prescribe medication for mental health conditions.']],
    ['what\'s the capital of Italy?', ['The capital of Italy is Rome.']],
    ['how do I make a budget?', ['To make a budget, list your income and expenses, set financial goals, and track your spending.']],
    ['can you help me find a job interview outfit?', ['Sure, what type of job are you interviewing for?']],
    ['what\'s the difference between a fact and an opinion?', ['A fact is a statement that can be proven to be true or false, while an opinion is a personal belief or judgment.']],
    ['what\'s the capital of Japan?', ['The capital of Japan is Tokyo.']],
    ['how do I change a tire?', ['To change a tire, first, find a safe location to pull over, then loosen the lug nuts, jack up the car, remove the lug nuts and old tire, install the new tire, and tighten the lug nuts.']],
    ['can you recommend a good place to go hiking?', ['Sure, where are you located?']],
    ['what\'s the difference between a virus and bacteria?', ['Viruses are microscopic infectious agents that require a host cell to reproduce, while bacteria are single-celled organisms that can reproduce independently.']],
    ['what\'s the capital of Russia?', ['The capital of Russia is Moscow.']],
    ['how do I start a garden?', ['To start a garden, choose a location with adequate sunlight, prepare the soil, select plants that are suitable for your climate, and water and maintain your garden regularly.']],
    ['can you help me find a good podcast?', ['Sure, what topics are you interested in?']],
    ['what\'s the difference between a democracy and a republic?', ['In a democracy, citizens directly participate in decision-making, while in a republic, citizens elect representatives to make decisions on their behalf.']],
    ['what\'s the capital of Spain?', ['The capital of Spain is Madrid.']],
    ['how do I make a resume?', ['To make a resume, include your contact information, a summary of your qualifications, work experience, education, skills, and any relevant certifications or awards.']],
    ['can you recommend a good place to travel?', ['Sure, where are you interested in traveling to?']],
    ['what\'s the difference between a lake and a pond?', ['Lakes are larger bodies of water that are typically deeper than ponds, while ponds are smaller bodies of water that may be shallow enough to support rooted plants.']],
    ['what\'s the capital of the United Kingdom?', ['The capital of the United Kingdom is London.']],
    ['how do I start a podcast?', ['To start a podcast, choose a topic, select recording equipment, record and edit your episodes, and distribute your podcast to platforms like iTunes and Spotify.']],
    ['can you help me find a good workout app?', ['Sure, what type of workouts are you interested in?']],
    ['what\'s the difference between a hurricane and a typhoon?', ['Hurricanes and typhoons are both tropical cyclones, but they are called hurricanes when they occur in the Atlantic and Northeast Pacific, and typhoons when they occur in the Northwest Pacific.']],
    ['what\'s the capital of China?', ['The capital of China is Beijing.']],
    ['how do I invest in stocks?', ['To invest in stocks, open a brokerage account, research companies, diversify your investments, and monitor the market regularly.']],
    ['can you recommend a good documentary?', ['Sure, what topics are you interested in?']],
    ['what\'s the difference between a mountain and a hill?', ['Mountains are taller and steeper than hills, and they are typically formed through tectonic processes, while hills are smaller and less steep.']],
    ['what\'s the capital of India?', ['The capital of India is New Delhi.']],
    ['how do I start a nonprofit organization?', ['To start a nonprofit organization, identify a mission, create a business plan, register your organization, and apply for tax-exempt status.']],
    ['can you help me find a good language learning app?', ['Sure, what language are you interested in learning?']],
    ['what\'s the difference between a cold and the flu?', ['Colds are usually milder than the flu and don\'t typically cause serious complications.']],
    ['what\'s the capital of South Africa?', ['The capital of South Africa is Pretoria.']],
    ['how do I create a website?', ['To create a website, choose a domain name, select a web hosting provider, design your website, and publish your content.']],
    ['can you recommend a good meditation app?', ['Sure, what type of meditation are you interested in?']],
    ['what\'s the difference between a comet and an asteroid?', ['Comets are icy bodies that originate from the outer solar system, while asteroids are rocky bodies that orbit the sun.']],
    ['what\'s the capital of Germany?', ['The capital of Germany is Berlin.']],
    ['how do I write a cover letter?', ['To write a cover letter, address it to the hiring manager, introduce yourself, explain why you\'re interested in the position, and highlight relevant qualifications and experiences.']],
    ['can you help me find a good cooking class?', ['Sure, what type of cuisine are you interested in learning?']],
    ['what\'s the difference between a credit card and a debit card?', ['A credit card allows you to borrow money from the card issuer, while a debit card allows you to spend money directly from your bank account.']],
    ['what\'s the capital of Australia?', ['The capital of Australia is Canberra.']],
    ['how do I start a blog?', ['Starting a blog involves choosing a topic, selecting a platform, and creating content.']],
    ['can you recommend a good movie to watch?', ['Sure, what genre are you in the mood for?']],
    ['what\'s the difference between a turtle and a tortoise?', ['Turtles are adapted for life in the water, while tortoises are adapted for life on land.']],
    ['what\'s the capital of Canada?', ['The capital of Canada is Ottawa.']],
    ['how do I cook rice?', ['To cook rice, rinse it thoroughly, add it to a pot with water, and simmer until the water is absorbed and the rice is tender.']],
    ['what\'s the largest ocean in the world?', ['The largest ocean in the world is the Pacific Ocean.']],
    ['can you help me find a good recipe?', ['Sure, what type of cuisine are you interested in?']],
    ['what\'s the difference between a psychologist and a psychiatrist?', ['Psychologists study human behavior and mental processes, while psychiatrists are medical doctors who can prescribe medication for mental health conditions.']],
    ['what\'s the capital of Italy?', ['The capital of Italy is Rome.']],
    ['how do I make a budget?', ['To make a budget, list your income and expenses, set financial goals, and track your spending.']],
    ['can you help me find a job interview outfit?', ['Sure, what type of job are you interviewing for?']],
    ['what\'s the difference between a fact and an opinion?', ['A fact is a statement that can be proven to be true or false, while an opinion is a personal belief or judgment.']],
    ['what\'s the capital of Japan?', ['The capital of Japan is Tokyo.']],
    ['how do I change a tire?', ['To change a tire, first, find a safe location to pull over, then loosen the lug nuts, jack up the car, remove the lug nuts and old tire, install the new tire, and tighten the lug nuts.']],
    ['what\'s the difference between a virus and bacteria?', ['Viruses are microscopic infectious agents that require a host cell to reproduce, while bacteria are single-celled organisms that can reproduce independently.']],
    ['what\'s the capital of Russia?', ['The capital of Russia is Moscow.']],
    ['can you help me find a good podcast?', ['Sure, what topics are you interested in?']],
    ['how do I start a garden?', ['To start a garden, choose a location with adequate sunlight, prepare the soil, select plants that are suitable for your climate, and water and maintain your garden regularly.']],
    ['what\'s the difference between a democracy and a republic?', ['In a democracy, citizens directly participate in decision-making, while in a republic, citizens elect representatives to make decisions on their behalf.']],
    ['what\'s the capital of Spain?', ['The capital of Spain is Madrid.']],
    ['how do I make a resume?', ['To make a resume, include your contact information, a summary of your qualifications, work experience, education, skills, and any relevant certifications or awards.']],
    ['can you recommend a good place to travel?', ['Sure, where are you interested in traveling to?']],
    ['what\'s the difference between a lake and a pond?', ['Lakes are larger bodies of water that are typically deeper than ponds, while ponds are smaller bodies of water that may be shallow enough to support rooted plants.']],
    ['what\'s the capital of the United Kingdom?', ['The capital of the United Kingdom is London.']],
    ['how do I start a podcast?', ['To start a podcast, choose a topic, select recording equipment, record and edit your episodes, and distribute your podcast to platforms like iTunes and Spotify.']],
    ['can you help me find a good workout app?', ['Sure, what type of workouts are you interested in?']],
    ['what\'s the difference between a hurricane and a typhoon?', ['Hurricanes and typhoons are both tropical cyclones, but they are called hurricanes when they occur in the Atlantic and Northeast Pacific, and typhoons when they occur in the Northwest Pacific.']],
    ['what\'s the capital of China?', ['The capital of China is Beijing.']],
    ['how do I invest in stocks?', ['To invest in stocks, open a brokerage account, research companies, diversify your investments, and monitor the market regularly.']],
    ['can you recommend a good documentary?', ['Sure, what topics are you interested in?']],
    ['what\'s the difference between a mountain and a hill?', ['Mountains are taller and steeper than hills, and they are typically formed through tectonic processes, while hills are smaller and less steep.']],
    ['what\'s the capital of India?', ['The capital of India is New Delhi.']],
    ['how do I start a nonprofit organization?', ['To start a nonprofit organization, identify a mission, create a business plan, register your organization, and apply for tax-exempt status.']],
    ['can you help me find a good language learning app?', ['Sure, what language are you interested in learning?']],
    ['what\'s the difference between a cold and the flu?', ['Colds are usually milder than the flu and don\'t typically cause serious complications.']],
    ['what\'s the capital of South Africa?', ['The capital of South Africa is Pretoria.']],
    ['how do I create a website?', ['To create a website, choose a domain name, select a web hosting provider, design your website, and publish your content.']],
    ['can you recommend a good meditation app?', ['Sure, what type of meditation are you interested in?']],
    ['what\'s the difference between a comet and an asteroid?', ['Comets are icy bodies that originate from the outer solar system, while asteroids are rocky bodies that orbit the sun.']],
    ['what\'s the capital of Germany?', ['The capital of Germany is Berlin.']],
    ['how do I write a cover letter?', ['To write a cover letter, address it to the hiring manager, introduce yourself, explain why you\'re interested in the position, and highlight relevant qualifications and experiences.']],
    ['can you help me find a good cooking class?', ['Sure, what type of cuisine are you interested in learning?']],
    ['what\'s the difference between a credit card and a debit card?', ['A credit card allows you to borrow money from the card issuer, while a debit card allows you to spend money directly from your bank account.']],
    ['what\'s the capital of Australia?', ['The capital of Australia is Canberra.']],
    ['how do I start a blog?', ['Starting a blog involves choosing a topic, selecting a platform, and creating content.']],
    ['can you recommend a good movie to watch?', ['Sure, what genre are you in the mood for?']],
    ['what\'s the difference between a turtle and a tortoise?', ['Turtles are adapted for life in the water, while tortoises are adapted for life on land.']],
    ['what\'s the capital of Canada?', ['The capital of Canada is Ottawa.']],
    ['how do I cook rice?', ['To cook rice, rinse it thoroughly, add it to a pot with water, and simmer until the water is absorbed and the rice is tender.']],
    ['what\'s the largest ocean in the world?', ['The largest ocean in the world is the Pacific Ocean.']],
    ['can you help me find a good recipe?', ['Sure, what type of cuisine are you interested in?']],
    ['what\'s the difference between a psychologist and a psychiatrist?', ['Psychologists study human behavior and mental processes, while psychiatrists are medical doctors who can prescribe medication for mental health conditions.']],
    ['what\'s the capital of Italy?', ['The capital of Italy is Rome.']],
    ['how do I make a budget?', ['To make a budget, list your income and expenses, set financial goals, and track your spending.']],

]


chatbot = Chat(pairs, reflections)


